### ISSUE TITLE
Add support for amino acids, vitamins and minerals

### ISSUE THREAD

**Issue by teolemon** [ubuntouch-fr/openfoodfacts#16]
We recently added support for vitamins and minerals in products.
In some cases, you will find what is below in a product:

Added vitamins:
Minerals:
Added amino acids:
Other nutritional substances added:
===== Vitamins and minerals detection =====

====== Vitamins ======

"vitamins_tags":["en:vitamin-a","en:cholecalciferol","en:vitamin-e","en:vitamin-c","en:thiamin","en:riboflavin","en:niacin","en:vitamin-b6","en:folic-acid","en:vitamin-b12","en:biotin","en:phylloquinone"]
====== Minerals ======

"minerals_tags":["en:calcium-citrate","en:potassium-citrate","en:sodium-citrate","en:magnesium-chloride","en:calcium-phosphate","en:potassium-phosphate","en:ferrous-sulphate","en:zinc-sulphate","en:cupric-sulphate","en:manganese-sulphate","en:sodium-carbonate","en:potassium-iodide"]
====== Amino acids ======

"amino_acids_tags":["en:l-tryptophan"]
====== Other nutritional substances =====

"other_nutritional_substances_tags":["en:taurine","en:inositol","en:choline-citrate","en:taurine","en:inositol","en:choline-citrate","en:taurine","en:inositol","en:choline-citrate"]

**Comment by sy-per** [comment]
Could you provide me with an article that contains one?

**Comment by teolemon** [comment]
It's probably not the highest needed feature. Closing
