### ISSUE TITLE
bottom icon barely visible in night mode

### ISSUE THREAD

**Issue by Danfro** [ubuntouch-fr/openfoodfacts#23]
The bottom icon is almost not visible in night mode. A brighter color would be more suitable here.

![screenshot20191106_223328999](https://user-images.githubusercontent.com/37637312/68339994-e9e79300-00e5-11ea-8d7b-8f9be0f99355.png)

**Comment by Nymerea** [comment]
From what I remember, the component we use is not maintened anymore and don't respect the theming.

There is  nothing we can do about this.

@sy-per  can you confirm ?

**Comment by Danfro** [comment]
Don't beat me, but that is the only example I have got ;-), the GoogleMaps webapp+ does use a different component. Maybe the component can be swapped?
Although the GoogleMaps app foes not theme at all.

Just an idea.

Otherwise there is the option to make a altered copy of the component within the app (not good, double code) or well, the upstream component would need an update.

But I am not sure it is worth the effort.

(me thinking loud ^^ in the hope it helps :-) )

On Wed, 6 Nov 2019 23:19:37 -0800, Nymerea wrote:
> From what I remember, the component we use is not maintened 
> anymore and don't respect the theming.
>
> There is  nothing we can do about this.
>
> @sy-per  can you confirm ?
>

--

**Comment by sy-per** [comment]
I think I can adapt it to follow the theme, for the next update ;) .

**Comment by sy-per** [comment]
The update is coming soon in the open-store, this problem is fixed in the commit:
eb4986ff9c1cd335133776e8e5889faff49613e4
