### ISSUE TITLE
[enhancement] make app respect system theme

### ISSUE THREAD

**Issue by Danfro** [ubuntouch-fr/openfoodfacts#24]
Although it is nice to have the option to switch between night mode and several colored themes, I would like to see system theme respected.

If system theme is suru-dark -> app is in night mode, otherwise in colored mode. Some other apps do provide this functionality.

=> system theme | ambiance theme | suru-dark theme

**Comment by sy-per** [comment]
This is the next step, review the ui.
thanks for your report

**Comment by sy-per** [comment]
I think I can adapt it to follow the theme, for the next update ;) .

**Comment by Danfro** [comment]
Sounds great!

On Wed, 6 Nov 2019 23:39:33 -0800, Jimmy wrote:
> I think I can adapt it to follow the theme, for the next update ;) .
>

--

**Comment by sy-per** [comment]
The update is coming soon in the open-store, this problem is fixed in the commit:
eb4986ff9c1cd335133776e8e5889faff49613e4

**Comment by Danfro** [comment]
Many thanks for the quick fix! 


On Fri, 8 Nov 2019 23:33:45 -0800, Jimmy wrote:
> The update is coming soon in the open-store, this problem is 
> fixed in the commit:
> eb4986ff9c1cd335133776e8e5889faff49613e4
>
>

--
