### ISSUE TITLE
[question] number of datasets

### ISSUE THREAD

**Issue by Danfro** [ubuntouch-fr/openfoodfacts#25]
The app description states that approximately 65.000 datasets are available for scanning.
The [internet page ](https://world.openfoodfacts.org/) gives over 1 Million registered datasets.

Is the app description outdated? Or can not all datasets be accessed via the app?

**Comment by Nymerea** [comment]
You're right, it's the app description that is outdated.

Thanks a lot for your report :-)

**Comment by Danfro** [comment]
I have to thank for your work to make the app working again.

On Wed, 6 Nov 2019 23:16:59 -0800, Nymerea wrote:
> You're right, it's the app description that is outdated.
>
> Thanks a lot for your report :-)
>

--

**Comment by sy-per** [comment]
Open-store.io updated

**Comment by Danfro** [comment]
Currently there are 1,040,202 items listed. I believe this number is going to change on a daily base.

May I suggest using something like this:
 "... access to over 1.000.000 records..."

**Comment by sy-per** [comment]
Corrected
