### ISSUE TITLE
It will be great to display bar code, if product was not found 

### ISSUE THREAD

**Issue by gang65** [ubuntouch-fr/openfoodfacts#3]
When I'm looking for product via bar code (for example via camera), and product is not found, currently it is displaying message:
"Your product was not found"

it will be great to display bar code in that code, if product was not found:

For example:
"Your product with barcode 123456789 was not found".
Then I could compare if application read barcode correctly.

It will be also nice to generate and display how such barcode should looks like.

**Comment by sy-per** [comment]
Hello,
Indeed the next update, this feature should be added.

Thank

**Comment by Nymerea** [comment]
Thank you for bug report.

Wait few day, and the bug will be closed
